title: PREDICT
url: https://predict-imhresearch.sg
favicon: /images/Logo/predict favicon.png
colors:
  primary-color: "#5471c0"
  secondary-color: "#a64d79"
  media-colors:
    - title: media-color-one
      color: "#243766"
    - title: media-color-two
      color: "#c7a879"
    - title: media-color-three
      color: "#a64d79"
    - title: media-color-four
      color: "#5cd0bb"
    - title: media-color-five
      color: "#756449"
description: Preventing Depression Through Research
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d2pbfp83ad6pg3.amplifyapp.com
prod: https://master.d15invg1m5z48.amplifyapp.com
facebook-pixel: ""
resources_name: media-center
shareicon: /images/2.png
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
